tabWidth: 2
semi: true
singleQuote: true
trailingComma: 'none'
arrowParens: 'always'
printWidth: 100
importOrderSeparation: true
importOrder: ['^@gittrends/(.*)$', '^[./]']
importOrderCaseInsensitive: true
