version: '3.7'

services:
  mongo:
    image: mongo:latest
    command: --wiredTigerJournalCompressor zstd --directoryperdb --auth
    restart: always
    ports:
      - ${GT_DATABASE_PORT-27017}:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GT_DATABASE_USERNAME-}
      MONGO_INITDB_ROOT_PASSWORD: ${GT_DATABASE_PASSWORD-}
      MONGO_INITDB_DATABASE: ${GT_DATABASE_DB-}

  redis:
    image: redis:alpine
    command: --maxmemory-policy allkeys-lru
    restart: always
    ports:
      - ${GT_REDIS_PORT-6379}:6379

volumes:
  db:
    name: gittrends.app
