version: '3.7'

services:
  mongo:
    build:
      context: ./packages/docker-autossh-tunnel/
      dockerfile: ./Dockerfile
    container_name: mongo
    restart: always
    volumes:
      - $HOME/.ssh:/root/ssh:ro
    ports:
      - ${GITTRENDS_DATABASE_PORT}:27017
    environment:
      TUNNEL_HOST: ${GITTRENDS_DATABASE_TUNEL_HOST}
      REMOTE_HOST: ${GITTRENDS_DATABASE_HOST}
      LOCAL_PORT: 27017
      REMOTE_PORT: 27017
