version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    command: --config /etc/mongo/mongod.conf --auth --replSet rs0
    ports:
      - ${GITTRENDS_DATABASE_PORT}:27017
    volumes:
      - db:/data/db
      - ./data/mongo:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GITTRENDS_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${GITTRENDS_DATABASE_DB}

  adminmongo:
    image: mrvautin/adminmongo:latest
    container_name: adminmongo
    restart: always
    ports:
      - ${GITTRENDS_ADMIN_MONGO_PORT}:1234
    environment:
      HOST: 0.0.0.0
      PORT: 1234
      CONN_NAME: mongo-docker
      DB_USERNAME: ${GITTRENDS_DATABASE_USERNAME}
      DB_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: ${GITTRENDS_DATABASE_DB}
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT}:6379
    command: --maxmemory 50mb --maxmemory-policy allkeys-lru

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data/nginx/development.conf:/app/data/nginx/default.conf:ro
      - nginx-cache:/var/cache
    environment:
      GITTRENDS_DATABASE_HOST: mongo
      GITTRENDS_DATABASE_PORT: 27017
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  db:
    name: gittrends.app
  pgadmin:
    name: pgadmin.gittrends.app
  nginx-cache:
    name: nginx.gittrends.app
