version: '3.7'

services:
  service:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    restart: unless-stopped
    volumes:
      - ${GT_PROXY_TOKENS_FILE-./tokens.txt}:/app/tokens.txt:ro
      - ./.env.local:/app/.env.local:ro
      - ./.env.${NODE_ENV-development}:/app/.env.${NODE_ENV-development}:ro
    env_file:
      - .env
