version: '3.7'

services:
  mongo:
    image: mongo:latest
    command: --wiredTigerCacheSizeGB ${GT_DATABASE_CACHE_SIZE-1} --wiredTigerJournalCompressor zstd --directoryperdb --auth
    restart: always
    ports:
      - ${GT_DATABASE_PORT-27017}:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GT_DATABASE_USERNAME-}
      MONGO_INITDB_ROOT_PASSWORD: ${GT_DATABASE_PASSWORD-}
      MONGO_INITDB_DATABASE: ${GT_DATABASE_DB-}

  redis:
    image: redis:alpine
    command: --maxmemory ${GT_REDIS_MAX_MEMORY-50}mb --maxmemory-policy allkeys-lru
    restart: always
    ports:
      - ${GT_REDIS_PORT-6379}:6379

  proxy-server:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    entrypoint: yarn github-proxy-server --tokens /tokens.txt --request-interval 250
    restart: unless-stopped
    volumes:
      - ./${GT_PROXY_TOKENS_FILE-./tokens.txt}:/tokens.txt:ro
    ports:
      - ${GT_PROXY_PORT-8081}:80
    environment:
      PORT: 80

  queue-board:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn queue-board
    restart: unless-stopped
    ports:
      - ${GT_QUEUE_BOARD_PORT-8082}:80
    environment:
      GT_REDIS_HOST: redis
      GT_REDIS_PORT: 6379
      PORT: 80
    depends_on:
      - redis

  scheduler:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn schedule all --wait 48 --cron "${GT_SCHEDULER_CRON-0 */6 * * *}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GT_DATABASE_HOST: mongo
      GT_DATABASE_PORT: 27017
      GT_REDIS_HOST: redis
      GT_REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

  updater:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn update --type repositories --workers ${GT_UPDATER_REPOS_WORKERS-1}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GT_DATABASE_HOST: mongo
      GT_DATABASE_PORT: 27017
      GT_REDIS_HOST: redis
      GT_REDIS_PORT: 6379
      GT_PROXY_HOST: proxy-server
      GT_PROXY_PORT: 80
    depends_on:
      - mongo
      - redis
      - proxy-server

  users-updater:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn update --type users --workers ${GT_UPDATER_USERS_WORKERS-1}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GT_DATABASE_HOST: mongo
      GT_DATABASE_PORT: 27017
      GT_REDIS_HOST: redis
      GT_REDIS_PORT: 6379
      GT_PROXY_HOST: proxy-server
      GT_PROXY_PORT: 80
    depends_on:
      - mongo
      - redis
      - proxy-server

volumes:
  db:
    name: gittrends.app
