version: '3.7'

services:
  mongo:
    image: mongo:latest
    command: --wiredTigerJournalCompressor zstd --directoryperdb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    logging:
      driver: local
      options:
        max-file: 5
        max-size: 10m

  redis:
    image: redis:alpine
    command: --maxmemory-policy allkeys-lru
    restart: unless-stopped
    ports:
      - 6379:6379
    logging:
      driver: local
      options:
        max-file: 5
        max-size: 10m

volumes:
  db:
    name: gittrends.app
