version: '3.7'

services:
  mongo-backup:
    image: istepanov/mongodump
    volumes:
      - ./mongo-backup:/backup
    environment:
      MONGO_URI: ${GT_MONGO_URL}
      CRON_SCHEDULE: ${GT_MONGODUMP_CRON_SCHEDULE-0 0 * * 0}

  mongo-backup-run:
    image: istepanov/mongodump
    volumes:
      - ./mongo-backup:/backup
    environment:
      MONGO_URI: ${GT_MONGO_URL}
