version: '3.7'

services:
  service:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: echo "Nothing to do here."
    env_file:
      - .env
    environment:
      GITTRENDS_DATABASE_HOST: mongo
      GITTRENDS_DATABASE_PORT: 27017
      GITTRENDS_REDIS_HOST: redis
      GITTRENDS_REDIS_PORT: 6379
      GITTRENDS_PROXY_HOST: proxy-server
      GITTRENDS_PROXY_PORT: 80
