version: '3.7'

services:
  postgres:
    image: postgres:alpine
    restart: always
    command: -N 500
    tty: true
    ports:
      - ${GITTRENDS_DATABASE_PORT}:5432
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${GITTRENDS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      POSTGRES_DB: ${GITTRENDS_DATABASE_DB}
    networks:
      - gittrends

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - ${GITTRENDS_PGADMIN_PORT}:80
    volumes:
      - 'pgadmin-db:/var/lib/pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gittrends.app
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - gittrends

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${GITTRENDS_DATABASE_DB}
      POSTGRES_USER: ${GITTRENDS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      POSTGRES_EXTRA_OPTS: -Z9 --schema=public --blobs
      SCHEDULE: '@weekly'
      BACKUP_KEEP_DAYS: 3
      BACKUP_KEEP_WEEKS: 3
      BACKUP_KEEP_MONTHS: 3
      HEALTHCHECK_PORT: 8888
    networks:
      - gittrends

  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT}:6379
    command: --maxmemory 50mb --maxmemory-policy allkeys-lru
    networks:
      - gittrends

  website-api:
    build:
      context: .
      dockerfile: ./packages/website-api/Dockerfile
    restart: always
    environment:
      GITTRENDS_DATABASE_HOST: postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - gittrends
    labels:
      - traefik.enable=true
      - traefik.http.routers.website-api.rule=(Host(`gittrends.app`) || Host(`www.gittrends.app`)) && PathPrefix(`/api`)
      - traefik.http.routers.website-api.entrypoints=web,websecure
      - traefik.http.routers.website-api.tls.certresolver=https-resolver
      - traefik.http.routers.website-api.middlewares=api-stripprefix
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api

  website-server:
    build:
      context: .
      dockerfile: ./packages/website/Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    restart: always
    depends_on:
      - website-api
    environment:
      GITTRENDS_API_HOST: website-api
      GITTRENDS_API_PORT: 80
    networks:
      - gittrends
    labels:
      - traefik.enable=true
      - traefik.http.routers.website-server.rule=Host(`gittrends.app`) || Host(`www.gittrends.app`)
      - traefik.http.routers.website-server.entrypoints=web,websecure
      - traefik.http.routers.website-server.tls.certresolver=https-resolver

  traefik:
    image: 'traefik:latest'
    restart: always
    command:
      # - --log.level=DEBUG
      - --api.dashboard=true
      # - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.https-resolver.acme.httpchallenge=true
      - --certificatesresolvers.https-resolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.https-resolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      # - --certificatesresolvers.https-resolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.https-resolver.acme.email=hudsonsilbor@gmail.com
      - --certificatesresolvers.https-resolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - website-api
      - website-server
    networks:
      - gittrends
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.gittrends.app`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=admin@gittrends.app:$$apr1$$tPnFN1yy$$X06fLb2niMBQKuQG1hPZ91

volumes:
  db:
    external: true
    name: gittrends.app
  pgadmin-db:
    name: pgadmin.gittrends.app

networks:
  gittrends:
    external: true
    name: gittrends.app
