version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT}:6379
    command: --maxmemory 50mb --maxmemory-policy allkeys-lru
