version: '3.7'

services:
  postgres:
    image: postgres:alpine
    restart: always
    command: -N 500
    ports:
      - ${GITTRENDS_DATABASE_PORT}:5432
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${GITTRENDS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      POSTGRES_DB: ${GITTRENDS_DATABASE_DB}
    networks:
      - gittrends

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - ${GITTRENDS_PGADMIN_PORT}:80
    volumes:
      - 'pgadmin-db:/var/lib/pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gittrends.app
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - gittrends

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${GITTRENDS_DATABASE_DB}
      POSTGRES_USER: ${GITTRENDS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      POSTGRES_EXTRA_OPTS: -Z9 --schema=public --blobs
      SCHEDULE: '@weekly'
      BACKUP_KEEP_DAYS: 3
      BACKUP_KEEP_WEEKS: 3
      BACKUP_KEEP_MONTHS: 3
      HEALTHCHECK_PORT: 8888
    networks:
      - gittrends

  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT}:6379
    command: --maxmemory 50mb --maxmemory-policy allkeys-lru
    networks:
      - gittrends

  website-api:
    build:
      context: .
      dockerfile: ./packages/website-api/Dockerfile
    restart: always
    environment:
      GITTRENDS_DATABASE_HOST: postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - gittrends

  website-server:
    build:
      context: .
      dockerfile: ./packages/website/Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    restart: always
    depends_on:
      - website-api
    environment:
      GITTRENDS_API_HOST: website-api
      GITTRENDS_API_PORT: 80
    networks:
      - gittrends

  nginx:
    image: nginx:alpine
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./data/nginx/development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - website-api
      - website-server
    ports:
      - 80:80
    networks:
      - gittrends

volumes:
  db:
    external: true
    name: gittrends.app
  pgadmin-db:
    name: pgadmin.gittrends.app

networks:
  gittrends:
    external: true
    name: gittrends.app
