version: '3.7'

services:
  mongo-backup:
    image: istepanov/mongodump
    volumes:
      - ./mongo-backup:/backup
    environment:
      MONGO_URI: 'mongodb://${GT_DATABASE_USERNAME}:${GT_DATABASE_PASSWORD}@mongo:27017/${GT_DATABASE_DB}?authSource=admin'
      CRON_SCHEDULE: ${GT_MONGODUMP_CRON_SCHEDULE-0 1 * * 0}
