version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: always
    command: --wiredTigerCacheSizeGB ${GITTRENDS_DATABASE_CACHE_SIZE-1} --wiredTigerJournalCompressor zstd --directoryperdb --auth
    ports:
      - ${GITTRENDS_DATABASE_PORT-27017}:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GITTRENDS_DATABASE_USERNAME-}
      MONGO_INITDB_ROOT_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD-}
      MONGO_INITDB_DATABASE: ${GITTRENDS_DATABASE_DB-}

  redis:
    image: redis:alpine
    restart: always
    command: --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - ${GITTRENDS_REDIS_PORT-6379}:6379

  proxy-server:
    extends:
      file: docker-compose.service.yml
      service: service
    entrypoint: npx @hsborges/github-proxy-server --tokens /tokens.txt --request-interval 250
    restart: unless-stopped
    volumes:
      - ./data/tokens.txt:/tokens.txt:ro
    ports:
      - ${GITTRENDS_PROXY_PORT-8081}:80
    environment:
      PORT: 80

  queue-board:
    extends:
      file: docker-compose.service.yml
      service: service
    restart: unless-stopped
    command: yarn queue-board
    ports:
      - ${GITTRENDS_QUEUE_BOARD_PORT-8082}:80
    environment:
      GITTRENDS_QUEUE_BOARD_PORT: 80
    depends_on:
      - redis

  scheduler:
    extends:
      file: docker-compose.service.yml
      service: service
    command: yarn schedule all --wait 168
    depends_on:
      - mongo
      - redis

  updater:
    extends:
      file: docker-compose.service.yml
      service: service
    restart: unless-stopped
    command: yarn update --type repositories --workers ${GITTRENDS_UPDATER_REPOS_WORKERS-1}
    environment:
      GITTRENDS_DATABASE_POOL_SIZE: ${GITTRENDS_DATABASE_POOL_SIZE-1}
    depends_on:
      - mongo
      - redis
      - proxy-server

  users-updater:
    extends:
      file: docker-compose.service.yml
      service: service
    restart: unless-stopped
    command: yarn update --type users --workers ${GITTRENDS_UPDATER_USERS_WORKERS-1}
    environment:
      GITTRENDS_DATABASE_POOL_SIZE: ${GITTRENDS_DATABASE_POOL_SIZE-1}
    depends_on:
      - mongo
      - redis
      - proxy-server

volumes:
  db:
    name: gittrends.app
