version: '3.7'

services:
  postgres:
    build:
      context: ./packages/docker-autossh-tunnel/
      dockerfile: ./Dockerfile
    container_name: postgres
    restart: always
    volumes:
      - $HOME/.ssh:/root/ssh:ro
    ports:
      - ${GITTRENDS_DATABASE_PORT}:5432
    environment:
      TUNNEL_HOST: ${GITTRENDS_DATABASE_TUNEL_HOST}
      REMOTE_HOST: ${GITTRENDS_DATABASE_HOST}
      LOCAL_PORT: 5432
      REMOTE_PORT: 5432
