version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    command: --config /etc/mongo/mongod.conf --auth
    ports:
      - ${GITTRENDS_DATABASE_PORT}:27017
    volumes:
      - db:/data/db
      - ./data/mongo:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GITTRENDS_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${GITTRENDS_DATABASE_DB}

  mongoku:
    image: huggingface/mongoku:latest
    container_name: mongoku
    restart: always
    ports:
      - ${GITTRENDS_MONGOKU_PORT}:8080
    volumes:
      - mongoku-db:/data
    environment:
      MONGOKU_SERVER_PORT: 8080
      MONGOKU_DATABASE_FILE: /data/mongoku.db
      MONGOKU_DEFAULT_HOST: mongodb://${GITTRENDS_DATABASE_USERNAME}:${GITTRENDS_DATABASE_PASSWORD}@mongo:${GITTRENDS_DATABASE_PORT}
    depends_on:
      - mongo

volumes:
  db:
    name: gittrends.app
  mongoku-db:
    name: gittrends.app
