version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-time-zone=+00:00 --max-connections=250 --default-authentication-plugin=mysql_native_password
    ports:
      - ${GITTRENDS_DATABASE_PORT}:3306
    volumes:
      - db:/var/lib/mysql
      - ./data/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: NYI4jsei5N4P
      MYSQL_USER: ${GITTRENDS_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${GITTRENDS_DATABASE_DB}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${GITTRENDS_PHPMYADMIN_PORT}:80
    environment:
      PMA_USER: ${GITTRENDS_DATABASE_USERNAME}
      PMA_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
    links:
      - mysql:db

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT}:6379
    command: --maxmemory 50mb --maxmemory-policy allkeys-lru

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data/nginx/development.conf:/app/data/nginx/default.conf:ro
    environment:
      GITTRENDS_DATABASE_HOST: mysql
      GITTRENDS_DATABASE_PORT: 3306
    env_file:
      - .env
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  db:
    external: true
    name: gittrends.app
