version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data/nginx/development.conf:/app/data/nginx/default.conf:ro
      - nginx-cache:/var/cache
    environment:
      GITTRENDS_DATABASE_HOST: mongo
      GITTRENDS_DATABASE_PORT: 27017
    env_file:
      - .env

volumes:
  nginx-cache:
    name: nginx.gittrends.app
