version: '3.7'

services:
  postgres:
    image: postgres:alpine
    restart: always
    command: -N 500
    ports:
      - ${GITTRENDS_DATABASE_PORT}:5432
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${GITTRENDS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      POSTGRES_DB: ${GITTRENDS_DATABASE_DB}
    networks:
      - gittrends

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - ${GITTRENDS_PGADMIN_PORT}:80
    volumes:
      - 'pgadmin-db:/var/lib/pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gittrends.app
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - gittrends

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${GITTRENDS_DATABASE_DB}
      POSTGRES_USER: ${GITTRENDS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      POSTGRES_EXTRA_OPTS: -Z9 --schema=public --blobs
      SCHEDULE: '@weekly'
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8888
    networks:
      - gittrends

  website-api:
    image: node:latest
    restart: always
    expose:
      - 80
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/packages/api
    command: yarn start --port 80
    depends_on:
      - postgres
    networks:
      - gittrends

  website-server:
    image: node:latest
    restart: always
    expose:
      - 80
    volumes:
      - .:/usr/src/app
    depends_on:
      - website-api
    working_dir: /usr/src/app/packages/website
    command: yarn start -H 0.0.0.0 -p 80
    environment:
      GITTRENDS_API_HOST: website-api
      GITTRENDS_API_PORT: 80
    networks:
      - gittrends

  website:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - website-api
      - website-server
    networks:
      - gittrends

volumes:
  db:
    external: true
    name: gittrends.app
  pgadmin-db:
    name: pgadmin.gittrends.app

networks:
  gittrends:
    external: true
