version: '3.7'

services:
  mongo-backup:
    image: istepanov/mongodump
    volumes:
      - ./mongo-backup:/backup
    environment:
      MONGO_URI: 'mongodb://${GITTRENDS_DATABASE_USERNAME}:${GITTRENDS_DATABASE_PASSWORD}@mongo:27017/${GITTRENDS_DATABASE_DB}?authSource=admin'
      CRON_SCHEDULE: ${GITTRENDS_MONGODUMP_CRON_SCHEDULE-0 1 * * 0}
