version: '3.7'

services:
  mongo:
    image: mongo:latest
    command: --wiredTigerCacheSizeGB ${GITTRENDS_DATABASE_CACHE_SIZE-1} --wiredTigerJournalCompressor zstd --directoryperdb --auth
    restart: always
    ports:
      - ${GITTRENDS_DATABASE_PORT-27017}:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GITTRENDS_DATABASE_USERNAME-}
      MONGO_INITDB_ROOT_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD-}
      MONGO_INITDB_DATABASE: ${GITTRENDS_DATABASE_DB-}

  redis:
    image: redis:alpine
    command: --maxmemory 100mb --maxmemory-policy allkeys-lru
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT-6379}:6379

  proxy-server:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    entrypoint: yarn github-proxy-server --tokens /tokens.txt --request-interval 250
    restart: unless-stopped
    volumes:
      - ./tokens.txt:/tokens.txt:ro
    ports:
      - ${GITTRENDS_PROXY_PORT-8081}:80
    environment:
      PORT: 80

  queue-board:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn queue-board
    restart: unless-stopped
    ports:
      - ${GITTRENDS_QUEUE_BOARD_PORT-8082}:80
    environment:
      GITTRENDS_REDIS_HOST: redis
      GITTRENDS_REDIS_PORT: 6379
      GITTRENDS_QUEUE_BOARD_PORT: 80
    depends_on:
      - redis

  scheduler:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn schedule all --wait 168 --cron "${GITTRENDS_SCHEDULER_CRON-0 */6 * * *}"
    env_file:
      - .env
    environment:
      GITTRENDS_DATABASE_HOST: mongo
      GITTRENDS_DATABASE_PORT: 27017
      GITTRENDS_REDIS_HOST: redis
      GITTRENDS_REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

  updater:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn update --type repositories --workers ${GITTRENDS_UPDATER_REPOS_WORKERS-1}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GITTRENDS_DATABASE_HOST: mongo
      GITTRENDS_DATABASE_PORT: 27017
      GITTRENDS_REDIS_HOST: redis
      GITTRENDS_REDIS_PORT: 6379
      GITTRENDS_PROXY_HOST: proxy-server
      GITTRENDS_PROXY_PORT: 80
    depends_on:
      - mongo
      - redis
      - proxy-server

  users-updater:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    image: gittrends-service:latest
    command: yarn update --type users --workers ${GITTRENDS_UPDATER_USERS_WORKERS-1}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GITTRENDS_DATABASE_HOST: mongo
      GITTRENDS_DATABASE_PORT: 27017
      GITTRENDS_REDIS_HOST: redis
      GITTRENDS_REDIS_PORT: 6379
      GITTRENDS_PROXY_HOST: proxy-server
      GITTRENDS_PROXY_PORT: 80
    depends_on:
      - mongo
      - redis
      - proxy-server

volumes:
  db:
    name: gittrends.app
