version: '3.7'

services:
  traefik:
    image: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  api:
    build:
      context: .
      dockerfile: packages/website-api/Dockerfile
    restart: always
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`api.localhost`)'
      - 'traefik.http.routers.api.entrypoints=web'

  website:
    build:
      context: .
      dockerfile: packages/website/Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI}
        GITTRENDS_WEBSITE_DATASOURCE_URL: ${GITTRENDS_WEBSITE_DATASOURCE_URL}
    command: yarn start -H 0.0.0.0 --port 80
    restart: always
    environment:
      GITHUB_REDIRECT_URI: http://api.localhost/authorize
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.website.rule=Host(`localhost`)'
      - 'traefik.http.routers.website.entrypoints=web'
