version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    command: -N 500
    ports:
      - ${GITTRENDS_DATABASE_PORT}:5432
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${GITTRENDS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${GITTRENDS_DATABASE_PASSWORD}
      POSTGRES_DB: ${GITTRENDS_DATABASE_DB}
    networks:
      - gittrends

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - ${GITTRENDS_PGADMIN_PORT}:80
    volumes:
      - 'pgadmin-db:/var/lib/pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gittrends.app
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - gittrends

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    container_name: pgbackups
    restart: always
    volumes:
      - /backups:/backups
    environment:
      - POSTGRES_HOST=${GITTRENDS_DATABASE_HOST}
      - POSTGRES_PORT=${GITTRENDS_DATABASE_PORT}
      - POSTGRES_DB=${GITTRENDS_DATABASE_DB}
      - POSTGRES_USER=${GITTRENDS_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${GITTRENDS_DATABASE_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@weekly
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=1
      - HEALTHCHECK_PORT=9999
    networks:
      - gittrends

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT}:6379
    command: --maxmemory 50mb --maxmemory-policy allkeys-lru
    networks:
      - gittrends

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    container_name: nginx
    restart: always
    volumes:
      - ./data/nginx/development.conf:/app/data/nginx/default.conf:ro
    environment:
      GITTRENDS_DATABASE_HOST: postgres
      GITTRENDS_DATABASE_PORT: 5432
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 80:80
    networks:
      - gittrends

volumes:
  db:
    external: true
    name: gittrends.app
  pgadmin-db:
    name: pgadmin.gittrends.app

networks:
  gittrends:
    external: true
    name: gittrends.app
