version: '3.7'

services:
  website-api:
    image: node:latest
    restart: always
    expose:
      - 80
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/packages/api
    command: yarn start --port 80
    networks:
      - gittrends

  website-server:
    image: node:latest
    restart: always
    expose:
      - 80
    volumes:
      - .:/usr/src/app
    depends_on:
      - website-api
    working_dir: /usr/src/app/packages/website
    command: yarn start -H 0.0.0.0 -p 80
    environment:
      GITTRENDS_API_HOST: website-api
      GITTRENDS_API_PORT: 80
    networks:
      - gittrends

  website:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - website-api
      - website-server
    networks:
      - gittrends

networks:
  gittrends:
    external: true
