version: '3.7'

services:
  mongo:
    image: mongo:latest
    command: --wiredTigerJournalCompressor zstd --directoryperdb
    restart: always
    ports:
      - ${GT_MONGO_PORT-27017}:27017
    volumes:
      - db:/data/db

  redis:
    image: redis:alpine
    command: --maxmemory-policy allkeys-lru
    restart: always
    ports:
      - ${GT_REDIS_PORT-6379}:6379

volumes:
  db:
    name: gittrends.app
