version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${GITTRENDS_REDIS_PORT}:6379
    command: --maxmemory 500mb --maxmemory-policy allkeys-lru
    networks:
      - gittrends

  proxy:
    image: node:latest
    restart: always
    ports:
      - ${GITTRENDS_PROXY_PORT}:80
    volumes:
      - ../../:/usr/src/app
    working_dir: /usr/src/app/packages/service
    command: npx github-proxy-server --port 80 --request-interval 50 --tokens ../../tokens.txt --verbose
    networks:
      - gittrends
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '5'

  service:
    image: node:latest
    restart: always
    ports:
      - ${GITTRENDS_QUEUE_BOARD_PORT}:8080
    depends_on:
      - proxy
    volumes:
      - ../..:/usr/src/app
    working_dir: /usr/src/app/packages/service
    command: /bin/bash -c "npx pm2 start pm2-ecosystem.yml && npx pm2 logs"
    environment:
      GITTRENDS_DATABASE_HOST: postgres
      GITTRENDS_REDIS_HOST: redis
      GITTRENDS_PROXY_HOST: proxy
      GITTRENDS_PROXY_PORT: 80
      BULL_BOARD_PORT: 8080
    networks:
      - gittrends
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '5'

networks:
  gittrends:
    external: true
