version: '3.7'

services:
  proxy:
    image: node:alpine
    container_name: github-proxy-server
    restart: always
    ports:
      - ${GITTRENDS_PROXY_PORT}:${GITTRENDS_PROXY_PORT}
    volumes:
      - ../../:/usr/src/app
    working_dir: /usr/src/app/packages/service
    command: npx github-proxy-server --port ${GITTRENDS_PROXY_PORT} --request-interval 50 --tokens ${GITHUB_TOKENS_FILE} --verbose
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '5'

  service:
    image: node:latest
    container_name: gittrends-service
    restart: always
    ports:
      - ${BULL_BOARD_PORT}:${BULL_BOARD_PORT}
    depends_on:
      - mongo
      - redis
      - proxy
    volumes:
      - ../..:/usr/src/app
    working_dir: /usr/src/app/packages/service
    command: /bin/bash -c "npx pm2 start pm2-ecosystem.yml && npx pm2 logs"
    env_file:
      - .env
    environment:
      GITTRENDS_MONGO_HOST: gittrends-db
      GITTRENDS_REDIS_HOST: gittrends-cache
      GITTRENDS_PROXY_HOST: github-proxy-server
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '5'
