version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - 'db:/data/db'

  redis:
    image: redis:alpine
    restart: always
    command: --maxmemory 250mb --maxmemory-policy volatile-lfu

  gittrends:
    build: .
    restart: always
    volumes:
      - './config:/usr/src/app/config'
    env_file:
      - ./.env
    environment:
      GITTRENDS_REDIS_HOST: redis
      GITTRENDS_REDIS_PORT: 6379
      GITTRENDS_MONGO_HOST: mongo
      GITTRENDS_MONGO_PORT: 27017

volumes:
  db:
    external: true
    name: gittrends.app-database
