env:
  commonjs: true
  es2020: true
  node: true
extends:
  - airbnb
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: { 'no-underscore-dangle': 0, 'no-await-in-loop': 0, 'prettier/prettier': error }
